config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resources :drugs, only: [:create]
  resources :refills, only: [:update]
  resources :prescriptions
  resources :users, except: [:destroy]
  root 'welcome#index'
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :prescriptions
  has_many :pharmacies, through: :prescriptions
  has_many :users, through: :prescriptions
  has_many :drugs, through: :prescriptions

  validates :first_name, :last_name, presence: true
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  has_many :prescriptions
  has_many :pharmacies, through: :prescriptions
  has_many :users, through: :prescriptions
  has_many :doctors, through: :prescriptions
  has_many :drug_interactions
  has_many :interactions, through: :drug_interactions

  validates :name, :rxcui, presence: true
  validates :rxcui, numericality: true

  scope :interacting_pair, -> (interaction) do
    joins(:drug_interactions).where('interaction_id = ?', interaction.id)
  end
  scope :interacting_drug, -> (interaction, drug) do
    joins(:drug_interactions).where('interaction_id = ? AND drug_id != ?', interaction.id, drug.id)
  end

  def self.valid?(drug_name)
    self.find_by_name(drug_name) ? true : !!Adapters::DrugClient.find_by_name(drug_name).rxcui
  end

  def interaction_data
    self.interactions.with_true_interactions.map do |interaction|
    { drug_name: Drug.interacting_drug(interaction, self).first.name,
      interaction: interaction.description }
    end.uniq
  end

  def persist_interactions(user)
    self.pair_with_active_drugs(user).reject do |drug_pair|
      drugs_persisted?(drug_pair) && drug_interaction_persisted?(drug_pair)
    end.each do |drug_pair|
      interaction = Adapters::InteractionClient.interactions(drug_pair)
      interaction.save
      DrugInteraction.create(drug_id: drug_pair[0].id, interaction_id: interaction.id)
      DrugInteraction.create(drug_id: drug_pair[1].id, interaction_id: interaction.id)
    end
  end

  def pair_with_active_drugs(user)
    user.prescriptions.active.reject do |prescription|
      prescription.drug.name == self.name
    end.map { |prescription| [self, prescription.drug] }.uniq
  end

  def drugs_persisted?(drug_pair)
    DrugInteraction.where(drug_id: drug_pair[0].id).count > 0 &&
    DrugInteraction.where(drug_id: drug_pair[1].id).count > 0
  end

  def drug_interaction_ids(drug)
    DrugInteraction.where(drug_id: drug.id).pluck(:interaction_id)
  end

  def drug_interaction_persisted?(drug_pair)
    drug_1_interaction_ids = drug_interaction_ids(drug_pair[0])
    drug_2_interaction_ids = drug_interaction_ids(drug_pair[1])
    (drug_1_interaction_ids & drug_2_interaction_ids).count > 0
  end
end

app/models/drug_interaction.rb
class DrugInteraction < ActiveRecord::Base
  belongs_to :drug
  belongs_to :interaction
end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  has_many :drug_interactions
  has_many :drugs, through: :drug_interactions

  scope :with_true_interactions, -> { where('description != ?', 'No interactions.') }
end

app/models/pharmacy.rb
class Pharmacy < ActiveRecord::Base
  has_many :prescriptions
  has_many :doctors, through: :prescriptions
  has_many :users, through: :prescriptions
  has_many :drugs, through: :prescriptions

  validates :name,  presence: true
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :drug
  belongs_to :doctor
  belongs_to :pharmacy
  belongs_to :user
  has_many :scheduled_doses

  validates :dose_size, :refills, :fill_duration, :start_date, presence: true
  validates :refills, :fill_duration, numericality: true

  scope :active, -> { where('end_date >= ? AND start_date <= ?', Date.today, Date.today) }
  scope :inactive, -> { where('end_date < ?', Date.today) }
  scope :ending_within_week, -> { where(end_date: Date.today..Date.today + 6).order(:end_date) }
  scope :time_of_day, -> (time_of_day) { joins(:scheduled_doses).where('time_of_day = ?', time_of_day).uniq }

  def doses_by_time_of_day(time_of_day)
    self.scheduled_doses.select {|dose| dose.time_of_day == time_of_day}.count
  end

  def refill
    if refills > 0
      self.refills -= 1
      self.end_date += self.fill_duration
      self.save
    end
  end

  def calculate_end_date
    self.end_date = self.start_date + self.fill_duration
    self.save
  end

  def format_date(date)
    date.strftime('%A, %B %d')
  end
end

app/models/scheduled_dose.rb
class ScheduledDose < ActiveRecord::Base
  belongs_to :prescription
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :prescriptions
  has_many :pharmacies, through: :prescriptions
  has_many :doctors, through: :prescriptions
  has_many :drugs, through: :prescriptions

  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def regimen(time_of_day)
    self.prescriptions.active.time_of_day(time_of_day).map do |prescription|
      { name: prescription.drug.name,
        dose_size: prescription.dose_size,
        doses: prescription.doses_by_time_of_day(time_of_day),
        interactions: prescription.drug.interaction_data.select do |interaction|
          self.active_drug_names.include?(interaction[:drug_name])
        end }
    end
  end

  def active_drug_names
    self.prescriptions.active.joins(:drug).pluck(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  before_action :authorized?

  private

  def authorized?
    redirect_to login_path if !logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  skip_before_action :authorized?

  def create
    drug_validity = Drug.valid?(params[:drug_name])
    render json: { validity: drug_validity }
  end
end

app/controllers/refills_controller.rb
class RefillsController < ApplicationController
  # skip_before_action :authorized?

  def update
    @prescription = Prescription.find(params[:id])
    @prescription.refill
    if Prescription.ending_within_week.include?(@prescription)
      @formatted_date = @prescription.format_date(@prescription.end_date)
      render(json: {prescription: @prescription, expSoon: true, expDate: @formatted_date}, include: [:drug])
    else
      render(json: {prescription: @prescription}, include: [:drug])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized?

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = 'Email or password is invalid.'
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized?, only: [:create]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
    render :partial => "/layouts/user_form", :locals => { :user => @user }
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for signing up!"
    else
      redirect_to root_path
    end
  end

  def update
    @user = current_user
    @user.update(user_params)
    @user.save
    render :nothing => true
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorized?

  def index
    @user = User.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/drug_interactions_helper.rb
module DrugInteractionsHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/scheduled_doses_helper.rb
module ScheduledDosesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_user_profile_modal.html.erb
<div class="modal fade" id="editUserProfileModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title" id="myModalLabel">Edit Profile</h4>
     </div>
     <div class="modal-body" id='user-modal' class="text-center">
       
     </div>
   </div>
 </div>
</div>

app/views/users/_expiring_soon.html.erb
<div class="col-xs-12" id="exp-soon-div">
  <h3 id="exp-soon-header">Prescriptions Ending Soon</h3>
  <table class="table" id="exp-soon-table">
    <tr>
      <th>Medication</th>
      <th>End Date</th>
      <th>Refills Remaining</th>
      <th>Got Your Refill?</th>
    </tr>
    <% @user.prescriptions.ending_within_week.each do |rx| %>
      <tr data-rxid='<%= rx.id %>'>
        <td class='table-data'><%= rx.drug.name %></td>
        <td class='table-data'><span><%= rx.format_date(rx.end_date) %></span></td>
        <td class='table-data'><span><%= rx.refills %></span></td>
        <td>
          <% if rx.refills > 0 %>
            <%= button_to 'Update Rx', prescription_path(rx.id), method: 'patch', params: {refill: true}, class: 'btn btn-primary-outline active', 'data-rxid': rx.id.to_s %>
          <% else %>
            <button class='btn btn-primary-outline no-refills' disabled=true><span>No Refills</span></button>
          <% end %>
        </td>
      <% end %></tr>
  </table>
</div>

app/views/users/_pillbox_cells.html.erb
<div class="col-xs-3 pillbox-cell pillbox-cell-morning">
  <div class='icon-container'><%= image_tag 'morning.png', class: 'morning-icon' %></div>
  <% @user.regimen('morning').each do |drug| %>
  <br><%= drug[:name] %> (<%= drug[:dose_size] %>)
  <% if drug[:doses] != 1 %>
    x<%= drug[:doses] %>
  <% end %>
    <% if drug[:interactions].length > 0 %>
      <div class='warning-icon-container'>
        <%= image_tag 'warning.png', class: 'warning-icon' %>
        <div class='warning-message'>
          <% drug[:interactions].each do |interaction| %>
            <p><span class='warning-headline'>Interacts with <%= interaction[:drug_name] %></span><br>
            <%= interaction[:interaction] %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div id='morning-highlight'></div>
</div>
<div class="col-xs-3 pillbox-cell pillbox-cell-afternoon">
  <div class='icon-container'><%= image_tag 'afternoon.png', class: 'afternoon-icon' %></div>
  <% @user.regimen('afternoon').each do |drug| %>
  <br><%= drug[:name] %> (<%= drug[:dose_size] %>)
  <% if drug[:doses] != 1 %>
    x<%= drug[:doses] %>
  <% end %>
    <% if drug[:interactions].length > 0 %>
      <div class='warning-icon-container'>
        <%= image_tag 'warning.png', class: 'warning-icon' %>
        <div class='warning-message'>
          <% drug[:interactions].each do |interaction| %>
            <p><span class='warning-headline'>Interacts with <%= interaction[:drug_name] %></span><br>
            <%= interaction[:interaction] %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="col-xs-3 pillbox-cell pillbox-cell-evening">
<div class='icon-container'><%= image_tag 'evening.png', class: 'evening-icon' %></div>
  <% @user.regimen('evening').each do |drug| %>
  <br><%= drug[:name] %> (<%= drug[:dose_size] %>)
  <% if drug[:doses] != 1 %>
    x<%= drug[:doses] %>
  <% end %>
    <% if drug[:interactions].length > 0 %>
      <div class='warning-icon-container'>
        <%= image_tag 'warning.png', class: 'warning-icon' %>
        <div class='warning-message'>
          <% drug[:interactions].each do |interaction| %>
            <p><span class='warning-headline'>Interacts with <%= interaction[:drug_name] %></span><br>
            <%= interaction[:interaction] %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="col-xs-3 pillbox-cell pillbox-cell-bedtime">
<div class='icon-container'><%= image_tag 'bedtime.png', class: 'bedtime-icon' %></div>
  <% @user.regimen('bedtime').each do |drug| %>
  <br><%= drug[:name] %> (<%= drug[:dose_size] %>)
  <% if drug[:doses] != 1 %>
    x<%= drug[:doses] %>
  <% end %>
    <% if drug[:interactions].length > 0 %>
      <div class='warning-icon-container'>
        <%= image_tag 'warning.png', class: 'warning-icon' %>
        <div class='warning-message'>
          <% drug[:interactions].each do |interaction| %>
            <p><span class='warning-headline'>Interacts with <%= interaction[:drug_name] %></span><br>
            <%= interaction[:interaction] %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='container-fluid'>
  <div class='pillbox-container'>
    <div class='row pillbox-row'>
      <div class='col-xs-12 pillbox-cell-head'>
        <%= Time.now.strftime('%A %B %d') %>, <%= Time.now.strftime('%Y') %>
      </div>
    </div>
    <div class='row pillbox-row' id='times-of-day'>
      <%= render partial: 'pillbox_cells' %>
    </div>
  </div>
  <div class='row' id='time-arrow-row'>
    <div class='col-xs-3 time-indicator'><span id='morning-time'></span></div>
    <div class='col-xs-3 time-indicator'><span id='afternoon-time'></span></div>
    <div class='col-xs-3 time-indicator'><span id='evening-time'></span></div>
    <div class='col-xs-3 time-indicator'><span id='night-time'></span></div>
  </div>
  <div class='row pillbox-row' id='refill-msgs'>
    <% if !@user.prescriptions.ending_within_week.empty? %>
      <%= render partial: 'expiring_soon' %>
    <% end %>
  </div>
</div>