config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, only: [:create, :destroy]
  resources :drugs, only: [:create]
  resources :refills, only: [:update]
  resources :prescriptions
  resources :users, except: [:destroy]
  root 'welcome#index'
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :prescriptions
  has_many :pharmacies, through: :prescriptions
  has_many :users, through: :prescriptions
  has_many :drugs, through: :prescriptions

  validates :first_name, :last_name, presence: true
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  has_many :prescriptions
  has_many :pharmacies, through: :prescriptions
  has_many :users, through: :prescriptions
  has_many :doctors, through: :prescriptions
  has_many :drug_interactions
  has_many :interactions, through: :drug_interactions

  validates :name, :rxcui, presence: true
  validates :rxcui, numericality: true

  scope :interacting_pair, -> (interaction) do
    joins(:drug_interactions).where('interaction_id = ?', interaction.id)
  end
  scope :interacting_drug, -> (interaction, drug) do
    joins(:drug_interactions).where('interaction_id = ? AND drug_id != ?', interaction.id, drug.id)
  end

  def self.valid?(drug_name)
    self.find_by_name(drug_name) ? true : !!Adapters::DrugClient.find_by_name(drug_name).rxcui
  end

  def interaction_data
    self.interactions.with_true_interactions.map do |interaction|
    { drug_name: Drug.interacting_drug(interaction, self).first.name,
      interaction: interaction.description }
    end.uniq
  end

  def persist_interactions(user)
    self.pair_with_active_drugs(user).reject do |drug_pair|
      drugs_persisted?(drug_pair) && drug_interaction_persisted?(drug_pair)
    end.each do |drug_pair|
      interaction = Adapters::InteractionClient.interactions(drug_pair)
      interaction.save
      DrugInteraction.create(drug_id: drug_pair[0].id, interaction_id: interaction.id)
      DrugInteraction.create(drug_id: drug_pair[1].id, interaction_id: interaction.id)
    end
  end

  def pair_with_active_drugs(user)
    user.prescriptions.active.reject do |prescription|
      prescription.drug.name == self.name
    end.map { |prescription| [self, prescription.drug] }.uniq
  end

  def drugs_persisted?(drug_pair)
    DrugInteraction.where(drug_id: drug_pair[0].id).count > 0 &&
    DrugInteraction.where(drug_id: drug_pair[1].id).count > 0
  end

  def drug_interaction_ids(drug)
    DrugInteraction.where(drug_id: drug.id).pluck(:interaction_id)
  end

  def drug_interaction_persisted?(drug_pair)
    drug_1_interaction_ids = drug_interaction_ids(drug_pair[0])
    drug_2_interaction_ids = drug_interaction_ids(drug_pair[1])
    (drug_1_interaction_ids & drug_2_interaction_ids).count > 0
  end
end

app/models/drug_interaction.rb
class DrugInteraction < ActiveRecord::Base
  belongs_to :drug
  belongs_to :interaction
end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  has_many :drug_interactions
  has_many :drugs, through: :drug_interactions

  scope :with_true_interactions, -> { where('description != ?', 'No interactions.') }
end

app/models/pharmacy.rb
class Pharmacy < ActiveRecord::Base
  has_many :prescriptions
  has_many :doctors, through: :prescriptions
  has_many :users, through: :prescriptions
  has_many :drugs, through: :prescriptions

  validates :name,  presence: true
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :drug
  belongs_to :doctor
  belongs_to :pharmacy
  belongs_to :user
  has_many :scheduled_doses

  validates :dose_size, :refills, :fill_duration, :start_date, presence: true
  validates :refills, :fill_duration, numericality: true

  scope :active, -> { where('end_date >= ? AND start_date <= ?', Date.today, Date.today) }
  scope :inactive, -> { where('end_date < ?', Date.today) }
  scope :ending_within_week, -> { where(end_date: Date.today..Date.today + 6).order(:end_date) }
  scope :time_of_day, -> (time_of_day) { joins(:scheduled_doses).where('time_of_day = ?', time_of_day).uniq }

  def doses_by_time_of_day(time_of_day)
    self.scheduled_doses.select {|dose| dose.time_of_day == time_of_day}.count
  end

  def refill
    if refills > 0
      self.refills -= 1
      self.end_date += self.fill_duration
      self.save
    end
  end

  def calculate_end_date
    self.end_date = self.start_date + self.fill_duration
    self.save
  end

  def format_date(date)
    date.strftime('%A, %B %d')
  end
end

app/models/scheduled_dose.rb
class ScheduledDose < ActiveRecord::Base
  belongs_to :prescription
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :prescriptions
  has_many :pharmacies, through: :prescriptions
  has_many :doctors, through: :prescriptions
  has_many :drugs, through: :prescriptions

  has_secure_password

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def regimen(time_of_day)
    self.prescriptions.active.time_of_day(time_of_day).map do |prescription|
      { name: prescription.drug.name,
        dose_size: prescription.dose_size,
        doses: prescription.doses_by_time_of_day(time_of_day),
        interactions: prescription.drug.interaction_data.select do |interaction|
          self.active_drug_names.include?(interaction[:drug_name])
        end }
    end
  end

  def active_drug_names
    self.prescriptions.active.joins(:drug).pluck(:name)
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  skip_before_action :authorized?

  def create
    drug_validity = Drug.valid?(params[:drug_name])
    render json: { validity: drug_validity }
  end
end

app/controllers/refills_controller.rb
class RefillsController < ApplicationController
  # skip_before_action :authorized?

  def update
    @prescription = Prescription.find(params[:id])
    @prescription.refill
    if Prescription.ending_within_week.include?(@prescription)
      @formatted_date = @prescription.format_date(@prescription.end_date)
      render(json: {prescription: @prescription, expSoon: true, expDate: @formatted_date}, include: [:drug])
    else
      render(json: {prescription: @prescription}, include: [:drug])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized?, only: [:create]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
    render :partial => "/layouts/user_form", :locals => { :user => @user }
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for signing up!"
    else
      redirect_to root_path
    end
  end

  def update
    @user = current_user
    @user.update(user_params)
    @user.save
    render :nothing => true
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorized?

  def index
    @user = User.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/pharmacies_helper.rb
module PharmaciesHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/scheduled_doses_helper.rb
module ScheduledDosesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title" id="myModalLabel">Log In</h4>
     </div>
     <div class="modal-body" class="text-center">
       <%= render "/sessions/session_login" %> 
     </div>
   </div>
 </div>
</div>

app/views/layouts/_sign_up_modal.html.erb
<div class="modal fade" id="signUpModal" tabindex="-5" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document" >
   <div class="modal-content">
     <div class="modal-header" >
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title" id="myModalLabel" ><div >Sign Up</div></h4>
     </div>
     <div class="modal-body" class="text-center">
       <%= render "layouts/user_form" %> 
     </div>
   </div>
 </div>
</div>

app/views/layouts/_user_form.html.erb
<div class='text-center'>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class='error messages'>
        <h2>Please correct the errors and resubmit the form.</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <div class="alert alert-danger" role="alert">
            <li><%= message %></li></div>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='field'>
      <p><%= f.label :first_name %><br>
      <%= f.text_field :first_name %></p>
    </div>
    <div class='field'>
      <p><%= f.label :last_name %><br>
      <%= f.text_field :last_name %></p>
    </div>
    <div class='field'>
      <p><%= f.label :email %><br>
      <%= f.text_field :email %></p>
    </div>
    <div class='field'>
      <p><%= f.label :password %><br>
      <%= f.password_field :password %></p>
    </div>
    <div class='field'>
      <p><%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %></p>
    </div>
    <br>
    <div class='actions'><%= f.submit class: "btn btn-primary", id: 'form-submit' %></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrescriptionManager</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= render "/prescriptions/new_prescription_modal" %>
    <%= render "/users/edit_user_profile_modal" %>
  <% else %>
    <%= render "layouts/login_modal" %>
    <%= render "layouts/sign_up_modal" %>
  <% end %>
    <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if current_user %>
          <%= link_to image_tag('logo.png', class: 'logo'), user_path(current_user) %>
        <% else %>
          <%= link_to image_tag('logo.png', class: 'logo'), root_path %>
        <% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Prescriptions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My Prescriptions', prescriptions_path, method: 'get' %></li>
              <li><a id='newPrescriptionButton' href="#" data-toggle="modal" data-target="#newPrescriptionModal">New Prescription</a></li>
            </ul>
          </li>
          <% end %>
        </ul>
        
        <% if flash[:error] %>
          <%= flash[:error] %>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="   false">Logged in as <%= current_user.first_name %><span class="caret"></span></a>
        <ul class="dropdown-menu">
              <%= javascript_tag "var userId = #{current_user.id};" %>
               <li><a id='editUserProfileButton' href="#" data-toggle="modal" data-target="#editUserProfileModal">Edit Profile</a></li>
               <li><%= link_to 'Log Out', logout_path, method: 'get' %></li>
        </ul>
                </li>
              <% else %>
                <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#signUpModal">
                  Sign Up
                </button>
                <button type="button" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#loginModal">
                Log In
                </button>

              <% end %>
            </div>
          </nav>
        </ul>
      </div>
    </div>
  </nav>
<%= yield %>
<div id="invalid-drug"></div>
</body>
</html>